In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib tk

import blp_fft

U = blp_fft.HexLattice(5)

In [7]:
U.eval_func(lambda x, y: x**2 + y)

In [3]:
U.transform()

In [5]:
U.inverse_transform()

In [6]:
A = [U.grids[0].copy(), U.grids[1].copy()]

In [4]:
U.coefs[0]

array([[ 5.00000000e-01+0.j, -2.76367947e-17+0.j,  5.00000000e-01+0.j,
         2.97494613e-17+0.j,  1.42096493e-17+0.j,  1.63772668e-17+0.j,
         3.85911315e-17+0.j,  6.89324642e-18+0.j, -1.36655893e-17+0.j,
        -1.34276023e-17+0.j, -5.06785232e-18+0.j,  1.12070661e-17+0.j,
        -2.22899521e-17+0.j, -2.02114071e-17+0.j, -1.49911561e-17+0.j,
        -2.77555756e-17+0.j, -2.48314958e-17+0.j,  2.77555756e-17+0.j],
       [-1.00000000e+00+0.j, -8.26757350e-17+0.j,  4.64544652e-19+0.j,
        -3.90249330e-17+0.j, -3.88219552e-17+0.j, -2.97548410e-17+0.j,
        -4.54292241e-17+0.j, -1.99125261e-17+0.j, -1.78349432e-17+0.j,
        -1.56480587e-17+0.j, -1.34032111e-17+0.j, -2.57631043e-17+0.j,
        -1.20360696e-17+0.j, -1.50397056e-17+0.j, -5.87649171e-18+0.j,
         4.16293756e-18+0.j, -3.03355285e-18+0.j,  0.00000000e+00+0.j],
       [-5.16609658e-19+0.j, -1.40355106e-18+0.j, -1.47582377e-17+0.j,
         9.13463912e-19+0.j, -2.17798766e-17+0.j,  2.53891484e-18+0.j,
    

In [29]:
from scipy import fft

A = np.arange(7)
B = fft.dct(A, type = 2)/14
#B[0] /= 2
#B[-1] /= 2
fft.dct(B, type=3)

array([3.33066907e-16, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
       4.00000000e+00, 5.00000000e+00, 6.00000000e+00])

In [9]:
A[1] - U.grids[1]

array([[-2.45029691e-16+0.j,  1.66533454e-16+0.j, -1.94289029e-16+0.j,
        -5.55111512e-17+0.j,  0.00000000e+00+0.j,  1.11022302e-16+0.j,
         1.11022302e-16+0.j,  0.00000000e+00+0.j, -1.11022302e-16+0.j,
         0.00000000e+00+0.j,  0.00000000e+00+0.j,  1.11022302e-16+0.j,
         1.11022302e-16+0.j, -1.11022302e-16+0.j, -2.77555756e-17+0.j,
         2.35922393e-16+0.j, -1.76941795e-16+0.j],
       [-5.55111512e-16+0.j, -1.66533454e-16+0.j, -4.71844785e-16+0.j,
        -1.66533454e-16+0.j, -2.77555756e-16+0.j, -2.22044605e-16+0.j,
        -2.22044605e-16+0.j, -2.22044605e-16+0.j, -3.33066907e-16+0.j,
        -1.11022302e-16+0.j, -1.11022302e-16+0.j, -1.11022302e-16+0.j,
        -5.55111512e-17+0.j, -2.22044605e-16+0.j, -3.05311332e-16+0.j,
        -1.24900090e-16+0.j, -3.74700271e-16+0.j],
       [-2.22044605e-16+0.j,  1.11022302e-16+0.j, -1.11022302e-16+0.j,
         6.93889390e-17+0.j,  0.00000000e+00+0.j,  1.11022302e-16+0.j,
         1.11022302e-16+0.j,  0.00000000e+00+0

In [1]:
import blp_fft as bf
import test

U = bf.CCLattice(7)
test.test_invertibility(U)

3.674103369967233e-15
3.676762674165972e-15


[array([[[5.20488360e-01, 5.04972921e-01, 3.39119565e-01, 2.22792664e-01,
          4.84475468e-01, 8.16011583e-01, 2.87727647e-01, 5.41306646e-01],
         [2.73346323e-01, 6.73318164e-01, 7.21342689e-01, 1.54406300e-01,
          8.04436910e-01, 6.44675901e-01, 7.17917281e-01, 6.39131349e-01],
         [3.00546281e-01, 4.39836118e-01, 2.77984961e-01, 7.81839657e-01,
          1.42628235e-01, 1.71670463e-01, 7.93020040e-02, 6.67652810e-02],
         [6.37639007e-01, 1.31401076e-01, 4.27131365e-01, 4.07869870e-01,
          2.36943445e-01, 9.95684248e-01, 1.68765450e-01, 2.61433479e-01],
         [1.58958090e-01, 7.97137982e-02, 9.68560046e-01, 9.11849817e-01,
          1.00153661e-02, 8.49276888e-01, 2.26470802e-01, 1.71843408e-01],
         [4.61373631e-01, 9.71221369e-01, 8.77948012e-01, 7.28219025e-01,
          6.13924790e-01, 1.87351626e-01, 6.09213638e-01, 5.27106758e-01],
         [3.56719093e-01, 2.47400468e-01, 9.55755536e-01, 5.02940337e-01,
          7.75853890e-01, 4.2367

In [3]:
U.grids

[array([[0.48833541, 0.48422171, 0.99832081, 0.97420586],
        [0.46104855, 0.40100239, 0.59312045, 0.16904479],
        [0.70862849, 0.30475714, 0.34410832, 0.52981472],
        [0.06056164, 0.39836805, 0.86470142, 0.44338017]]),
 array([[0.4606223 , 0.9967546 , 0.57713896],
        [0.15118146, 0.15713801, 0.55326938],
        [0.43431399, 0.24809513, 0.74546179],
        [0.92065913, 0.88734773, 0.1055166 ]])]

In [5]:
import blp_fft as bf
import test
import numpy as np
%matplotlib tk
f = lambda x, y: np.exp(-30*(x**2 + y**2))
df = lambda x, y: 2*x*np.exp(-(x**2 + y**2))
U = bf.PadLattice(20)
test.test_deriv(U, 0, f, df)

1.4100176773079922
0.9367703887258199


In [6]:
U.max_degree

array([0., 0., 0.])

In [5]:
U.d_in[0:49]

array([ 0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        2.34479103e-13])

In [1]:
A = U.grids[0].copy()
U.eval_func(f)
print(A - U.grids[0])

NameError: name 'U' is not defined

In [6]:
%matplotlib tk
U.make_integral_stencil()

In [7]:
U.eval_func(f)

In [8]:
U.get_integral()

[0.10426451201925477]

In [2]:
j = (-1, -1, -1)
for i in U.axis_sort[0]:
    if i[:3] == j[:3]:
        print(i)
    j = i[:3]

In [5]:
np.sqrt(3)*8

13.856406460551018

In [3]:
for ind in np.ndindex(x.shape):
    if np.isnan(x[ind]):
        continue
    if np.isnan(y[ind]):
        continue
    
    print(ind, (x[ind] - y[ind])/(y[ind] + 1e-8), x[ind])

(0, 0, 0) 1.495082499218211e-12 5.39055936353642
(0, 0, 1) 4.529709970242249e-09 -2.042810365310288e-17
(0, 0, 2) 4.2188028738517233e-11 2.6144171146091812
(0, 0, 3) 3.907985030019808e-09 8.171241461241152e-17
(0, 0, 4) 1.1964555495460215e-08 0.3234502729311264
(0, 0, 5) 0.0 0.0
(0, 0, 6) 4.617089352904177e-06 0.026815085816508794
(0, 0, 7) 1.2434497928813208e-08 8.171241461241152e-17
(0, 0, 8) 0.0020762845751074724 0.0016741938697502068
(0, 0, 9) -5.773159706514912e-09 -2.042810365310288e-17
(0, 0, 10) 1.5462736171615152e-05 8.336412180254271e-05
(0, 1, 0) -6.819544983197066e-09 -1.48020484758149e-16
(0, 1, 1) 1.3065508742723008e-25 3.0814879110195774e-33
(0, 1, 2) 3.0977093819542127e-09 -4.0963553038989804e-17
(0, 1, 3) -3.1369546934179298e-25 -3.9258155986389416e-33
(0, 1, 4) 1.3122750600725045e-08 9.250469920236224e-17
(0, 1, 5) 0.0 0.0
(0, 1, 6) 1.1418803682965312e-08 6.955526537003954e-17
(0, 1, 7) -5.546678239835244e-27 -8.443276876193643e-34
(0, 1, 8) -1.2650558757560429e-08 -7

In [18]:
U.coefs[1]

array([[[ 8.33641218e-05, -2.22044605e-17,  4.04568000e-05,
          3.19744231e-17,  5.41671290e-06,  0.00000000e+00],
        [ 2.54518628e-17,  1.54074396e-33, -1.08327750e-16,
          6.96416268e-34,  7.63148447e-17,  0.00000000e+00],
        [ 1.67419387e-03, -7.27317236e-17,  8.11994983e-04,
          8.35011456e-17,  1.00657906e-04, -6.35528743e-17],
        [ 2.48689958e-17,  2.31111593e-33, -7.19788848e-17,
         -3.15544362e-33,  9.41826557e-17,  0.00000000e+00],
        [ 2.68150858e-02, -2.44994721e-17,  1.30052974e-02,
         -2.95747247e-18,  1.60901316e-03, -4.93420196e-17]],

       [[-1.62925229e-17, -6.16297582e-33,  1.01673806e-16,
         -3.68892622e-33,  1.35082483e-17,  0.00000000e+00],
        [ 1.59004776e-33,  0.00000000e+00, -3.16126315e-33,
         -5.47382213e-51, -7.39900550e-34,  0.00000000e+00],
        [-8.30487293e-17, -9.64516190e-33,  3.83800036e-17,
         -7.99260927e-33, -4.75308247e-17,  0.00000000e+00],
        [ 9.28298233e-35, -3.8

In [9]:
for i in U.axis_sort[0]:
    if i[:3] == (6, 0, 10):
        print(i)

In [17]:
U.get_point_count()

3059

In [9]:
import blp_fft as bf

%matplotlib tk

U = bf.FCCLattice(10)
U.plot_basis()

In [10]:
U.axis_sort[0]

[(0, 0, 0, 1, 0, 0, 0, 0),
 (1, 0, 0, 1, 0, 1, 0, 0),
 (2, 0, 0, 1, 0, 2, 0, 0),
 (3, 0, 0, 1, 0, 3, 0, 0),
 (4, 0, 0, 1, 0, 4, 0, 0),
 (5, 0, 0, 1, 0, 5, 0, 0),
 (6, 0, 0, 1, 0, 6, 0, 0),
 (7, 0, 0, 1, 0, 7, 0, 0),
 (8, 0, 0, 1, 0, 8, 0, 0),
 (9, 0, 0, 1, 0, 9, 0, 0),
 (10, 0, 0, 1, 0, 10, 0, 0),
 (11, 0, 0, 1, 1, 9, 0, 0),
 (12, 0, 0, 1, 1, 8, 0, 0),
 (13, 0, 0, 1, 1, 7, 0, 0),
 (14, 0, 0, 1, 1, 6, 0, 0),
 (15, 0, 0, 1, 1, 5, 0, 0),
 (16, 0, 0, 1, 1, 4, 0, 0),
 (17, 0, 0, 1, 1, 3, 0, 0),
 (18, 0, 0, 1, 1, 2, 0, 0),
 (19, 0, 0, 1, 1, 1, 0, 0),
 (20, 0, 0, 1, 3, 0, 0, 0),
 (0, 1, 0, 1, 0, 0, 1, 0),
 (1, 1, 0, 1, 0, 1, 1, 0),
 (2, 1, 0, 1, 0, 2, 1, 0),
 (3, 1, 0, 1, 0, 3, 1, 0),
 (4, 1, 0, 1, 0, 4, 1, 0),
 (5, 1, 0, 1, 0, 5, 1, 0),
 (6, 1, 0, 1, 0, 6, 1, 0),
 (7, 1, 0, 1, 0, 7, 1, 0),
 (8, 1, 0, 1, 0, 8, 1, 0),
 (9, 1, 0, 1, 0, 9, 1, 0),
 (10, 1, 0, 1, 0, 10, 1, 0),
 (11, 1, 0, 1, 1, 9, 1, 0),
 (12, 1, 0, 1, 1, 8, 1, 0),
 (13, 1, 0, 1, 1, 7, 1, 0),
 (14, 1, 0, 1, 1, 6, 1, 0),
 (15, 1, 0